### PR TITLE
[WIP] Add social meta tags for Twitter, Google, Facebook, Github

### LINKED ISSUE #49: Add social meta tags for Twitter, Google, Facebook

### PR DESCRIPTION
**Pull request by eragon512**
Closes #49 

@arjun27 do you guys have any links for your FB/Twitter/Google pages?

### CODE REVIEW

**Comment by arjun27** [comment]
Nice to meet you @eragon512. My understanding was that social meta tags are already done - can you confirm @asanjeevrao?

We don't have twitter etc pages, and I don't think it is a priority to set them up. If we want to increase social engagement, it would be nice to be able to have quick share buttons - for after a successfully submission or to share updated info about a store.

**Comment by eragon512** [comment]
Ah, is this a low priority issue? My bad

**Comment by asanjeevrao** [comment]
Hey @eragon512 nice to connect with you - thanks for taking a shot at this! This task was primarily to make sure our website link has the right text and image set up for sharing on social channels - that's been set up now. 

Sent you an email with my whatsapp number - drop me a line there and I'll add you to a developer group for this project. There's a lot more we need to do on the front end side and we would love to have you onboard.

**Comment by arjun27** [comment]
> Ah, is this a low priority issue? My bad

Our bad here - we should keep the issues up to date.

**Pull request closed without merging**
